remote_theme: b2a3e8/jekyll-theme-console
title: xfavatax
twitter: xfavatax
url: "mfavata.github.io"

header_pages:
  - index.md

style: dark

footer: 'follow us on <a href="https://twitter.com/xfavatax">twitter</a>'
