title: xfavatax
url: "mfavata.github.io"

header_pages:
  - index.md

style: dark

footer: '<a href='/cgi-bin/webring.cgi?before=https://mfavata.github.io/'>&lt;&lt;&lt;</a> this site is part of the <a href='/cgi-bin/webring.cgi'>[haunted webring]</a> <a href='/cgi-bin/webring.cgi?after=https://mfavata.github.io/'>&gt;&gt;&gt;</a> follow me on <a href="https://haunted.computer/@xfavatax">mastodon</a>'

remote_theme: mfavata/jekyll-theme-console
